apiVersion: v1
kind: Namespace
metadata:
  name: prod
spec:
  selector:
    matchLabels:
      app: prod
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: prod
    spec:
      containers:
      - name: prod
        image: nginx:1.14.2
        ports:
        - containerPort: 80